version: '3'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5003:80"

  ui:
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=db;Database=BirthdayTracker;user=sa;password=BirthdayTracker1234!;MultipleActiveResultSets=true"
    ports:
      - "5004:80"

  db:
    environment:
      SA_PASSWORD: "BirthdayTracker1234!"
      ACCEPT_EULA: "Y"